# Food facts

data source: http://world.openfoodfacts.org/data/en.openfoodfacts.org.products.csv

In [4]:
import pandas as pd
import numpy as np

According to https://world.openfoodfacts.org/data

```
CSV Data Export
Data for all products, or some of the products, can be downloaded in CSV format (readable with OpenOffice, Excel and many other software) through the advanced search form.

Link : http://world.openfoodfacts.org/data/en.openfoodfacts.org.products.csv

The file encoding is Unicode UTF-8. The character that separates fields is <tab> (tabulation).
```

In [8]:
df = pd.read_csv('food-facts.csv', sep='\t', low_memory=False)

In [9]:
df.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,0000000003087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0000000004530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,0000000004559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,0000000016087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,0000000016094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

How many rows do we have?

Summarizing information

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 363449 entries, 0 to 363448
Columns: 163 entries, code to water-hardness_100g
dtypes: float64(107), object(56)
memory usage: 452.0+ MB

What are the columns?

In [11]:
df.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

What is the name of the 100th column?

In [20]:
df.columns[[100,105]]

Index(['cholesterol_100g', '-fructose_100g'], dtype='object')

What is the type of the 100th column?

In [21]:
df.dtypes[['cholesterol_100g', '-fructose_100g']]

cholesterol_100g    float64
-fructose_100g      float64
dtype: object

In [25]:
df.index

RangeIndex(start=0, stop=363449, step=1)

In [28]:
df.iloc[18]['product_name']

'Lotus Organic Brown Jasmine Rice'

In [31]:
df.describe()

,no_nutriments,additives_n,ingredients_from_palm_oil_n,ingredients_from_palm_oil,ingredients_that_may_be_from_palm_oil_n,ingredients_that_may_be_from_palm_oil,nutrition_grade_uk,energy_100g,energy-from-fat_100g,fat_100g,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
count,0.0,290699.000000,290699.000000,0.0,290699.000000,0.0,0.0,3.024520e+05,873.000000,2.867720e+05,...,3251.000000,486.000000,195.000000,1437.000000,0.0,276.000000,261904.000000,261904.000000,0.0,0.0
mean,NaN,1.865053,0.024145,NaN,0.060430,NaN,NaN,1.130262e+03,585.614250,5.464389e+04,...,33.456158,60.163354,15.343590,52.009882,NaN,328.336249,9.169910,8.974086,NaN,NaN
std,NaN,2.495428,0.155416,NaN,0.282353,NaN,NaN,2.757582e+03,712.317698,2.925555e+07,...,32.879021,30.088169,3.658051,19.076232,NaN,403.931305,8.992364,9.146460,NaN,NaN
min,NaN,0.000000,0.000000,NaN,0.000000,NaN,NaN,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,8.000000,6.000000,NaN,0.000000,-15.000000,-15.000000,NaN,NaN
25%,NaN,0.000000,0.000000,NaN,0.000000,NaN,NaN,3.850000e+02,49.400000,1.000000e-01,...,0.000000,45.000000,12.000000,33.000000,NaN,80.975000,1.000000,1.000000,NaN,NaN
50%,NaN,1.000000,0.000000,NaN,0.000000,NaN,NaN,1.090000e+03,300.000000,5.300000e+00,...,25.000000,58.000000,15.000000,52.000000,NaN,189.500000,10.000000,9.000000,NaN,NaN
75%,NaN,3.000000,0.000000,NaN,0.000000,NaN,NaN,1.674000e+03,900.000000,2.000000e+01,...,55.000000,94.200000,15.000000,70.000000,NaN,372.900000,16.000000,16.000000,NaN,NaN
max,NaN,30.000000,2.000000,NaN,6.000000,NaN,NaN,1.428171e+06,3830.000000,1.566667e+10,...,100.000000,100.000000,25.000000,100.000000,NaN,2842.000000,40.000000,40.000000,NaN,NaN